# Generated by Django 4.2.30 on 2026-07-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('model_key', models.CharField(max_length=64)),
                ('model_label', models.CharField(max_length=128)),
                ('model_version', models.CharField(max_length=32)),
                ('dataset', models.CharField(max_length=64)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('taxonomy_version', models.CharField(blank=True, max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('flagged_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('missing_columns', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'prediction batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('web', 'Dashboard upload'), ('api', 'REST API')], default='web', max_length=8)),
                ('customer_ref', models.CharField(blank=True, max_length=128)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text="The customer's feature values as supplied. Retention of this field is governed by BDSS_LOG_INPUT_DATA; switching it off keeps the reasons and the score while discarding the personal data behind them.")),
                ('model_key', models.CharField(db_index=True, max_length=64)),
                ('model_label', models.CharField(max_length=128)),
                ('model_version', models.CharField(db_index=True, max_length=32)),
                ('dataset', models.CharField(max_length=64)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('predicted_label', models.CharField(max_length=64)),
                ('predicted_churn', models.BooleanField(default=False)),
                ('probability', models.FloatField(help_text='Calibrated probability of churn.')),
                ('confidence', models.FloatField(help_text='Probability of the class the model actually assigned.')),
                ('band', models.CharField(choices=[('high', 'High risk'), ('medium', 'Medium risk'), ('low', 'Low risk')], max_length=8)),
                ('top_drivers', models.JSONField(default=list, help_text='Ranked SHAP drivers, strongest first.')),
                ('recommendation', models.CharField(max_length=255)),
                ('business_owner', models.CharField(max_length=64)),
                ('priority', models.CharField(choices=[('P1', 'P1 - act now'), ('P2', 'P2 - act this cycle'), ('P3', 'P3 - monitor')], db_index=True, max_length=4)),
                ('priority_score', models.FloatField(default=0.0)),
                ('rule_id', models.CharField(blank=True, max_length=64)),
                ('rationale', models.TextField(blank=True)),
                ('taxonomy_version', models.CharField(blank=True, max_length=32)),
                ('caveats', models.JSONField(blank=True, default=list)),
                ('override_action', models.CharField(blank=True, choices=[('accepted', 'Accepted as recommended'), ('different_offer', 'Actioned, but with a different offer'), ('no_action', 'No action taken - recommendation rejected'), ('wrong_risk', 'Risk estimate looks wrong'), ('already_resolved', 'Already handled or recently renewed')], max_length=32)),
                ('override_reason', models.TextField(blank=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='dashboard.predictionbatch')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'priority'], name='dashboard_p_batch_i_81a497_idx'), models.Index(fields=['created_at', 'model_key'], name='dashboard_p_created_205973_idx')],
            },
        ),
    ]
